webtalk_init -webtalk_dir D:\\Xilinx_2019_2\\RTL_prj\\OCOWFC_Z19\\OCOWFC_Z19\\Z19_NFC_4Chanel\\Z19_NFC_4Channel\\vitis\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2026-04-22 16:23:40" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vitis v2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "Vitis" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "pilvsqdghdh7tk701s54l9emrd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.2_7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-12500" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.850 GB" -context "user_environment"
webtalk_register_client -client vitis
webtalk_add_data -client vitis -key uid -value "1776845427624" -context "vitis\\\\platform/1776845427624"
webtalk_add_data -client vitis -key platform_source -value "dsa" -context "vitis\\\\platform/1776845427624"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\platform/1776845427624"
webtalk_add_data -client vitis -key processor -value "psu_cortexa53" -context "vitis\\\\platform/1776845427624"
webtalk_add_data -client vitis -key platform -value "NA" -context "vitis\\\\platform/1776845427624"
webtalk_transmit -clientid 122484748 -regid "" -xml D:\\Xilinx_2019_2\\RTL_prj\\OCOWFC_Z19\\OCOWFC_Z19\\Z19_NFC_4Chanel\\Z19_NFC_4Channel\\vitis\\webtalk\\usage_statistics_ext_vitis.xml -html D:\\Xilinx_2019_2\\RTL_prj\\OCOWFC_Z19\\OCOWFC_Z19\\Z19_NFC_4Chanel\\Z19_NFC_4Channel\\vitis\\webtalk\\usage_statistics_ext_vitis.html -wdm D:\\Xilinx_2019_2\\RTL_prj\\OCOWFC_Z19\\OCOWFC_Z19\\Z19_NFC_4Chanel\\Z19_NFC_4Channel\\vitis\\webtalk\\vitis_webtalk.wdm -intro "<H3>Vitis Usage Report</H3><BR>"
webtalk_terminate
