# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/NFC_4Channel_bd_nfc_top_0_0.xci
# IP: The module: 'NFC_4Channel_bd_nfc_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_res_fifo/asyn_res_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==asyn_res_fifo || ORIG_REF_NAME==asyn_res_fifo} -quiet] -quiet

# IP: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_req_fifo/asyn_req_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==asyn_req_fifo || ORIG_REF_NAME==asyn_req_fifo} -quiet] -quiet

# IP: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_fifo_rd/asyn_fifo_rd.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==asyn_fifo_rd || ORIG_REF_NAME==asyn_fifo_rd} -quiet] -quiet

# IP: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_fifo_wr/asyn_fifo_wr.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==asyn_fifo_wr || ORIG_REF_NAME==asyn_fifo_wr} -quiet] -quiet

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_res_fifo/asyn_res_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asyn_res_fifo || ORIG_REF_NAME==asyn_res_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_res_fifo/asyn_res_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asyn_res_fifo || ORIG_REF_NAME==asyn_res_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_req_fifo/asyn_req_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asyn_req_fifo || ORIG_REF_NAME==asyn_req_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_req_fifo/asyn_req_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asyn_req_fifo || ORIG_REF_NAME==asyn_req_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_fifo_rd/asyn_fifo_rd.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asyn_fifo_rd || ORIG_REF_NAME==asyn_fifo_rd} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_fifo_rd/asyn_fifo_rd_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asyn_fifo_rd || ORIG_REF_NAME==asyn_fifo_rd} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_fifo_wr/asyn_fifo_wr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asyn_fifo_wr || ORIG_REF_NAME==asyn_fifo_wr} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_fifo_wr/asyn_fifo_wr_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asyn_fifo_wr || ORIG_REF_NAME==asyn_fifo_wr} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: D:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/NFC_4Channel_bd_nfc_top_0_0.xci
# IP: The module: 'NFC_4Channel_bd_nfc_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_res_fifo/asyn_res_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==asyn_res_fifo || ORIG_REF_NAME==asyn_res_fifo} -quiet] -quiet

# IP: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_req_fifo/asyn_req_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==asyn_req_fifo || ORIG_REF_NAME==asyn_req_fifo} -quiet] -quiet

# IP: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_fifo_rd/asyn_fifo_rd.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==asyn_fifo_rd || ORIG_REF_NAME==asyn_fifo_rd} -quiet] -quiet

# IP: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_fifo_wr/asyn_fifo_wr.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==asyn_fifo_wr || ORIG_REF_NAME==asyn_fifo_wr} -quiet] -quiet

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_res_fifo/asyn_res_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asyn_res_fifo || ORIG_REF_NAME==asyn_res_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_res_fifo/asyn_res_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asyn_res_fifo || ORIG_REF_NAME==asyn_res_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_req_fifo/asyn_req_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asyn_req_fifo || ORIG_REF_NAME==asyn_req_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_req_fifo/asyn_req_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asyn_req_fifo || ORIG_REF_NAME==asyn_req_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_fifo_rd/asyn_fifo_rd.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asyn_fifo_rd || ORIG_REF_NAME==asyn_fifo_rd} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_fifo_rd/asyn_fifo_rd_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asyn_fifo_rd || ORIG_REF_NAME==asyn_fifo_rd} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_fifo_wr/asyn_fifo_wr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asyn_fifo_wr || ORIG_REF_NAME==asyn_fifo_wr} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/src/asyn_fifo_wr/asyn_fifo_wr_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asyn_fifo_wr || ORIG_REF_NAME==asyn_fifo_wr} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
