# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin_constrain.xdc

# Block Designs: bd/NFC_4Channel_bd/NFC_4Channel_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd || ORIG_REF_NAME==NFC_4Channel_bd} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_zynq_ultra_ps_e_0_0/NFC_4Channel_bd_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==NFC_4Channel_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_smartconnect_0_0/NFC_4Channel_bd_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_smartconnect_0_0 || ORIG_REF_NAME==NFC_4Channel_bd_smartconnect_0_0} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_nfc_top_0_0/NFC_4Channel_bd_nfc_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_nfc_top_0_0 || ORIG_REF_NAME==NFC_4Channel_bd_nfc_top_0_0} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_axi_dma_0_0/NFC_4Channel_bd_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_axi_dma_0_0 || ORIG_REF_NAME==NFC_4Channel_bd_axi_dma_0_0} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_axi_dma_0_2/NFC_4Channel_bd_axi_dma_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_axi_dma_0_2 || ORIG_REF_NAME==NFC_4Channel_bd_axi_dma_0_2} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_axi_dma_0_3/NFC_4Channel_bd_axi_dma_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_axi_dma_0_3 || ORIG_REF_NAME==NFC_4Channel_bd_axi_dma_0_3} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_axi_dma_0_4/NFC_4Channel_bd_axi_dma_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_axi_dma_0_4 || ORIG_REF_NAME==NFC_4Channel_bd_axi_dma_0_4} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_smartconnect_0_1/NFC_4Channel_bd_smartconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_smartconnect_0_1 || ORIG_REF_NAME==NFC_4Channel_bd_smartconnect_0_1} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_axi_bram_ctrl_0_0/NFC_4Channel_bd_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_axi_bram_ctrl_0_0 || ORIG_REF_NAME==NFC_4Channel_bd_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_axi_bram_ctrl_0_1/NFC_4Channel_bd_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_axi_bram_ctrl_0_1 || ORIG_REF_NAME==NFC_4Channel_bd_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_axi_bram_ctrl_0_2/NFC_4Channel_bd_axi_bram_ctrl_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_axi_bram_ctrl_0_2 || ORIG_REF_NAME==NFC_4Channel_bd_axi_bram_ctrl_0_2} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_axi_bram_ctrl_0_3/NFC_4Channel_bd_axi_bram_ctrl_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_axi_bram_ctrl_0_3 || ORIG_REF_NAME==NFC_4Channel_bd_axi_bram_ctrl_0_3} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_clk_wiz_0_0/NFC_4Channel_bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_clk_wiz_0_0 || ORIG_REF_NAME==NFC_4Channel_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_proc_sys_reset_0_0/NFC_4Channel_bd_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==NFC_4Channel_bd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_axi_bram_ctrl_0_bram_0/NFC_4Channel_bd_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==NFC_4Channel_bd_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_axi_bram_ctrl_1_bram_0/NFC_4Channel_bd_axi_bram_ctrl_1_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_axi_bram_ctrl_1_bram_0 || ORIG_REF_NAME==NFC_4Channel_bd_axi_bram_ctrl_1_bram_0} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_axi_bram_ctrl_2_bram_0/NFC_4Channel_bd_axi_bram_ctrl_2_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_axi_bram_ctrl_2_bram_0 || ORIG_REF_NAME==NFC_4Channel_bd_axi_bram_ctrl_2_bram_0} -quiet] -quiet

# IP: bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_axi_bram_ctrl_3_bram_0/NFC_4Channel_bd_axi_bram_ctrl_3_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NFC_4Channel_bd_axi_bram_ctrl_3_bram_0 || ORIG_REF_NAME==NFC_4Channel_bd_axi_bram_ctrl_3_bram_0} -quiet] -quiet

# XDC: bd/NFC_4Channel_bd/NFC_4Channel_bd_ooc.xdc
