# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_axi_bram_ctrl_3_bram_0/NFC_4Channel_bd_axi_bram_ctrl_3_bram_0.xci
# IP: The module: 'NFC_4Channel_bd_axi_bram_ctrl_3_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_axi_bram_ctrl_3_bram_0/NFC_4Channel_bd_axi_bram_ctrl_3_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'NFC_4Channel_bd_axi_bram_ctrl_3_bram_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_axi_bram_ctrl_3_bram_0/NFC_4Channel_bd_axi_bram_ctrl_3_bram_0.xci
# IP: The module: 'NFC_4Channel_bd_axi_bram_ctrl_3_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx_2019_2/RTL_prj/OCOWFC_Z19/OCOWFC_Z19/Z19_NFC_4Chanel/Z19_NFC_4Channel/Z19_NFC_4Channel.srcs/sources_1/bd/NFC_4Channel_bd/ip/NFC_4Channel_bd_axi_bram_ctrl_3_bram_0/NFC_4Channel_bd_axi_bram_ctrl_3_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'NFC_4Channel_bd_axi_bram_ctrl_3_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
